### PR TITLE
Add multimap! macro

### PR DESCRIPTION
**Pull request by dfaust**
Add a `multimap!` macro plus some minor fixes.

### CODE REVIEW

**Review by thejpster — COMMENTED** [review]
Thank you so much for this. I'm so happy someone else found this crate useful enough to send a PR!

Could you briefly explain the macro - I can't quite work out what's going on, especially as it's recursive. Could you also change the test to verify the macro had actually created the multimap you expect it to. I wonder if we should implement PartialEq - it might make those macro tests easier as we could check for equality with a hand built multimap.

Thanks!

**Comment by dfaust** [comment]
The macro is pretty much copied from https://github.com/bluss/maplit, so to be honest I'm not 100% sure what it does myself :). Unfortunately I couldn't find anything about calculating the length of the macro arguments. The recursion is due to the macro being re-used to perform multiple calculation steps using the prefixes `@single` and `@count`.
The last two arms are the entry points. The first has a trailing comma, the second doesn't. In case of a trailing comma it is stripped away and the macro is called again.
At first the length of the arguments is calculated by calling the macro with the `@count` prefix.
The length is then used to allocate enough memory.
After that all arguments are inserted into the map.

> Could you also change the test to verify the macro had actually created the multimap you expect it to

sure

Implementing `PartialEq` would make sense `Debug` probably as well (needed for `assert!`).

**Comment by thejpster** [comment]
Right, gotcha. Thanks.

**Comment by thejpster** [comment]
Superb.

**Comment by thejpster** [comment]
Submitted 1.1.0.

**Pull request merged**
